---
name: "Update Modules base"

on:
  workflow_dispatch:
        
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  update-Modules:
    runs-on: ubuntu-22.04
    env:
      COMMIT_NAME: github-actions[bot]
      COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com    
    steps:
      - name: Clone Firmware
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get update branch name
        id: branch-name
        run: echo "branch-name=update-modules-${{ steps.extract_branch.outputs.branch }}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Invoke update-modules
        run: ./contrib/update-modules.sh
            
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: '[Update] ${{ steps.extract_branch.outputs.branch }} modules'
          body: |
            Update modules for ${{ steps.extract_branch.outputs.branch }} branche
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          commit-message: bump modules version
          branch: ${{ steps.branch-name.outputs.branch-name }}
          
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"